import { Question, QuestionType } from './types';

// Based on "TRAINING WORKBOOK: English for Libya (Prep 3)" provided by the user
export const QUESTION_BANK: Question[] = [
  // --- Module 1 ---
  {
    id: 'm1-v-1',
    module: 'Module 1',
    section: 'Vocabulary',
    type: QuestionType.MCQ,
    text: '"Windproof" means:',
    options: ['Material that wind cannot get through', 'A window that is broken', 'A car engine'],
    correctAnswer: 'Material that wind cannot get through',
  },
  {
    id: 'm1-v-2',
    module: 'Module 1',
    section: 'Vocabulary',
    type: QuestionType.MCQ,
    text: 'A "queue" is:',
    options: ['A type of question', 'A line of people waiting for something', 'A security guard'],
    correctAnswer: 'A line of people waiting for something',
  },
  {
    id: 'm1-v-3',
    module: 'Module 1',
    section: 'Vocabulary',
    type: QuestionType.MCQ,
    text: 'If someone is "hard working," they are:',
    options: ['Lazy', 'Putting a lot of effort into something', 'Very sporty'],
    correctAnswer: 'Putting a lot of effort into something',
  },
  {
    id: 'm1-v-4',
    module: 'Module 1',
    section: 'Vocabulary',
    type: QuestionType.TRUE_FALSE,
    text: 'A "shop assistant" works in a hospital.',
    correctAnswer: false,
  },
  {
    id: 'm1-g-1',
    module: 'Module 1',
    section: 'Grammar',
    type: QuestionType.MCQ,
    text: 'Which sentence uses the correct adjective order?',
    options: ['She has black beautiful curly hair', 'She has beautiful curly black hair', 'She has curly beautiful black hair'],
    correctAnswer: 'She has beautiful curly black hair',
  },
  {
    id: 'm1-g-2',
    module: 'Module 1',
    section: 'Grammar',
    type: QuestionType.MCQ,
    text: 'Complete the compound noun: "Information ____"',
    options: ['shop', 'desk', 'park'],
    correctAnswer: 'desk',
  },
  {
    id: 'm1-r-1',
    module: 'Module 1',
    section: 'Reading (Panther 3.0D)',
    type: QuestionType.TRUE_FALSE,
    text: 'The Panther 3.0D is strictly a two-seater car.',
    correctAnswer: false,
  },
  {
    id: 'm1-r-2',
    module: 'Module 1',
    section: 'Reading (Panther 3.0D)',
    type: QuestionType.MCQ,
    text: 'The Panther 3.0D runs:',
    options: ['12 kilometers to the litre', '5 kilometers to the litre', '20 kilometers to the litre'],
    correctAnswer: '12 kilometers to the litre',
  },

  // --- Module 2 ---
  {
    id: 'm2-g-1',
    module: 'Module 2',
    section: 'Grammar',
    type: QuestionType.MCQ,
    text: 'Complete: "I\'d rather _____ to the beach."',
    options: ['go', 'to go', 'going'],
    correctAnswer: 'go',
  },
  {
    id: 'm2-g-2',
    module: 'Module 2',
    section: 'Grammar',
    type: QuestionType.MCQ,
    text: 'Complete: "How about _____ to the park?"',
    options: ['go', 'to go', 'going'],
    correctAnswer: 'going',
  },
  {
    id: 'm2-r-1',
    module: 'Module 2',
    section: 'Reading (Titanic)',
    type: QuestionType.MCQ,
    text: 'The film "Titanic" was released in:',
    options: ['1990', '1997', '2005'],
    correctAnswer: '1997',
  },
  {
    id: 'm2-r-2',
    module: 'Module 2',
    section: 'Reading (Lucy Fisher)',
    type: QuestionType.MCQ,
    text: 'Lucy Fisher plays a character named:',
    options: ['Samara', 'Sarah', 'Salma'],
    correctAnswer: 'Samara',
  },
  {
    id: 'm2-r-3',
    module: 'Module 2',
    section: 'Reading (Lucy Fisher)',
    type: QuestionType.MCQ,
    text: 'What did the brother put in the mother\'s tea?',
    options: ['Milk', 'Salt', 'Pepper'],
    correctAnswer: 'Salt',
  },

  // --- Module 3 ---
  {
    id: 'm3-g-1',
    module: 'Module 3',
    section: 'Grammar',
    type: QuestionType.TRUE_FALSE,
    text: '"The dawn is more beautiful than the night."',
    correctAnswer: true,
  },
  {
    id: 'm3-g-2',
    module: 'Module 3',
    section: 'Grammar',
    type: QuestionType.MCQ,
    text: 'Complete the comparison: "A bear is _____ than a wolf."',
    options: ['big', 'bigger', 'more big'],
    correctAnswer: 'bigger',
  },
  {
    id: 'm3-r-1',
    module: 'Module 3',
    section: 'Reading (Nature)',
    type: QuestionType.TRUE_FALSE,
    text: 'Falcons are the fastest things in the natural world.',
    correctAnswer: true,
  },
  {
    id: 'm3-r-2',
    module: 'Module 3',
    section: 'Reading (Nature)',
    type: QuestionType.MCQ,
    text: 'How fast can a falcon dive?',
    options: ['100 kph', '240 kph', '300 kph'],
    correctAnswer: '240 kph',
  },
  {
    id: 'm3-r-3',
    module: 'Module 3',
    section: 'Reading (Nature)',
    type: QuestionType.MCQ,
    text: 'Where can Mediterranean monk seals be found in Libya?',
    options: ['In the desert', 'Along the coast', 'In the mountains'],
    correctAnswer: 'Along the coast',
  },

  // --- Module 4 (Skills Review) ---
  {
    id: 'm4-s-1',
    module: 'Module 4',
    section: 'Skills',
    type: QuestionType.TRUE_FALSE,
    text: 'When listening, people often say important words louder and slower.',
    correctAnswer: true,
  },
  {
    id: 'm4-w-1',
    module: 'Module 4',
    section: 'Writing',
    type: QuestionType.MCQ,
    text: '"Drafting" means:',
    options: ['Writing the final version immediately', 'Writing a first version to check ideas', 'Copying from a book'],
    correctAnswer: 'Writing a first version to check ideas',
  },
  {
    id: 'm4-sp-1',
    module: 'Module 4',
    section: 'Speaking',
    type: QuestionType.TRUE_FALSE,
    text: 'You should always ask "Closed Questions" (Yes/No) to keep a conversation going.',
    correctAnswer: false,
  },

  // --- Module 5 (Media) ---
  {
    id: 'm5-v-1',
    module: 'Module 5',
    section: 'Vocabulary',
    type: QuestionType.MCQ,
    text: 'Where would you find football results in a newspaper?',
    options: ['Home News', 'Business', 'Sport'],
    correctAnswer: 'Sport',
  },
  {
    id: 'm5-r-1',
    module: 'Module 5',
    section: 'Reading',
    type: QuestionType.MCQ,
    text: 'How old is John Smith (the boy who saved the child)?',
    options: ['10', '13', '26'],
    correctAnswer: '13',
  },
  {
    id: 'm5-g-1',
    module: 'Module 5',
    section: 'Grammar',
    type: QuestionType.MCQ,
    text: 'Choose the correct form: "I _____ when the phone rang."',
    options: ['slept', 'was sleeping', 'sleep'],
    correctAnswer: 'was sleeping',
  },

  // --- Module 6 (Jobs) ---
  {
    id: 'm6-v-1',
    module: 'Module 6',
    section: 'Vocabulary',
    type: QuestionType.MCQ,
    text: 'A mechanic works in a:',
    options: ['Hospital', 'Garage', 'School'],
    correctAnswer: 'Garage',
  },
  {
    id: 'm6-v-2',
    module: 'Module 6',
    section: 'Vocabulary',
    type: QuestionType.MCQ,
    text: 'An architect:',
    options: ['Flies planes', 'Plans buildings', 'Writes books'],
    correctAnswer: 'Plans buildings',
  },
  {
    id: 'm6-r-1',
    module: 'Module 6',
    section: 'Reading',
    type: QuestionType.MCQ,
    text: 'Dr. Wadea Tarhuni is a specialist in:',
    options: ['The heart (Cardiologist)', 'The teeth (Dentist)', 'Bones'],
    correctAnswer: 'The heart (Cardiologist)',
  },
  {
    id: 'm6-r-2',
    module: 'Module 6',
    section: 'Reading',
    type: QuestionType.TRUE_FALSE,
    text: 'Dr. Wadea invented a device to monitor heartbeats remotely.',
    correctAnswer: true,
  },
  {
    id: 'm6-g-1',
    module: 'Module 6',
    section: 'Grammar',
    type: QuestionType.MCQ,
    text: '"I have a plan. I _____ be a doctor."',
    options: ['will', 'am going to', 'am'],
    correctAnswer: 'am going to',
  },

  // --- Module 7 (Countries) ---
  {
    id: 'm7-g-1',
    module: 'Module 7',
    section: 'Grammar',
    type: QuestionType.MCQ,
    text: 'Choose the correct Passive form: "Cotton _____ in Sudan."',
    options: ['is grown', 'grows', 'is growing'],
    correctAnswer: 'is grown',
  },
  {
    id: 'm7-g-2',
    module: 'Module 7',
    section: 'Grammar',
    type: QuestionType.MCQ,
    text: 'Present Perfect: "I _____ to England."',
    options: ['have been', 'was', 'am'],
    correctAnswer: 'have been',
  },
  {
    id: 'm7-r-1',
    module: 'Module 7',
    section: 'Reading',
    type: QuestionType.MCQ,
    text: 'In Holland, people often ride:',
    options: ['Camels', 'Bicycles', 'Rickshaws'],
    correctAnswer: 'Bicycles',
  },
  {
    id: 'm7-r-2',
    module: 'Module 7',
    section: 'Reading',
    type: QuestionType.TRUE_FALSE,
    text: 'The "Ghibli" is a cold, wet wind.',
    correctAnswer: false,
  },
  {
    id: 'm7-r-3',
    module: 'Module 7',
    section: 'Reading',
    type: QuestionType.MCQ,
    text: 'The capital of Sudan is:',
    options: ['Tripoli', 'Khartoum', 'Cairo'],
    correctAnswer: 'Khartoum',
  },

  // --- Module 8 (Storytelling) ---
  {
    id: 'm8-r-1',
    module: 'Module 8',
    section: 'Reading (Stork-Ruler)',
    type: QuestionType.MCQ,
    text: 'The ruler bought a box of:',
    options: ['Old coins', 'Magic sweets', 'Jewellery'],
    correctAnswer: 'Magic sweets',
  },
  {
    id: 'm8-r-2',
    module: 'Module 8',
    section: 'Reading (Stork-Ruler)',
    type: QuestionType.MCQ,
    text: 'When the ruler ate the sweet, he turned into a:',
    options: ['Lion', 'Stork', 'Frog'],
    correctAnswer: 'Stork',
  },
  {
    id: 'm8-r-3',
    module: 'Module 8',
    section: 'Reading (Unusual Journey)',
    type: QuestionType.MCQ,
    text: 'Rania found a missing:',
    options: ['Dog', 'Cat', 'Bird'],
    correctAnswer: 'Cat',
  },
  {
    id: 'm8-r-4',
    module: 'Module 8',
    section: 'Reading (Unusual Journey)',
    type: QuestionType.TRUE_FALSE,
    text: 'The cat was famous and appeared on TV.',
    correctAnswer: true,
  },
];

export const MOCK_STUDENTS: import('./types').Student[] = [
  { id: 's1', name: 'Ali Ahmed', results: [] },
  { id: 's2', name: 'Sara Mahmoud', results: [] },
  { id: 's3', name: 'Omar Khaled', results: [] },
];
